### ISSUE TITLE
warn  - Url '/' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap

### ISSUE THREAD

**Issue by CodiTrixta** [supershaneski/openai-whisper#2]
Hey I followed the step and every time I start it up I just get a black screen and if I look in the console this is what I get:

```
ready - started server on 0.0.0.0:3006, url: http://localhost:3006
info  - Defining routes from exportPathMap
event - compiled client and server successfully in 526 ms (158 modules)
warn  - Url '/' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap
warn  - Url '/' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap
wait  - compiling / (client and server)...
event - compiled client and server successfully in 211 ms (206 modules)
warn  - Url '/' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap
wait  - compiling /api/transcribe (client and server)...
event - compiled successfully in 68 ms (63 modules)
```

anything im doing wrong?

**Comment by CodiTrixta** [comment]
@supershaneski or @ladrua 
Can you please help me?

**Comment by ladrua** [comment]
Hi! Sorry, I just tested this repo for a day, and added some code to the repo for docker support. I am sure @supershaneski can help you though :) Best of luck!

**Comment by CodiTrixta** [comment]
Just to let you know, I have been able to get it working but I still receive this warning. If u set the MinDecibels too low it throws an error but you dont know that as no error gets logged out. Had to find it the hard way

```
handleError(error) {

        console.log(error)
        
        this.setState({
            error: true,
        })
    }
```

This helped me out

**Comment by supershaneski** [comment]
Thank you for the heads up. I updated the code to prevent it. 

For reference of others who might encounter the same problem, when AnalyserNode.minDecibels is the same as AnalyserNode.maxDecibels, it will throw an INDEX_SIZE_ERR. The default value of maxDecibels is -30dB.

To fix, just set different maxDecibels value
```
const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
const analyser = audioCtx.createAnalyser();
analyser.minDecibels = -30;
analyser.maxDecibels = -10;
```
